# -*- mode: zsh; sh-indentation: 2; indent-tabs-mode: nil; sh-basic-offset: 2; -*-
# vim: ft=zsh sw=2 ts=2 et

export TERM=${TERM:-xterm-256color}
export SHELL=${SHELL:-${commands[zsh]}}
export ZI_DATA=${ZI_DATA:-/data}
export ZI_BIN=${ZI_BIN:-${XDG_DATA_HOME:-${HOME}/.local/share}/zi/bin}
