# -*- mode: zsh; sh-indentation: 2; indent-tabs-mode: nil; sh-basic-offset: 2; -*-
# vim: ft=zsh sw=2 ts=2 et

export TERM=${TERM:-xterm-256color}
export SHELL=${SHELL:-${commands[zsh]}}

typeset -Ag ZI

export ZI[HOME_DIR]=${ZI_HOME_DIR:-/data}
export ZI[BIN_DIR]=${ZI_BIN_DIR:-$HOME/.zi/bin}
