source /src/docker/utils.zsh

zi::prepare
zi::install

autoload -Uz _zi
(( ${+_comps} )) && _comps[zi]=_zi

zi::init

typeset -U path
path=("${ZPFX:-${HOME}/.zi/polaris}/bin" "${HOME}/go/bin" $path)

if [[ -n "$ZI_ZSH_VERSION" ]]
then
  zi::pack-zsh "$ZI_ZSH_VERSION"
fi
