source /src/docker/utils.zsh

typeset -U path
path=("${ZPFX:-${HOME}/.zi/polaris}/bin" "${HOME}/go/bin" $path)

zi::prepare; zi::install; zi::init
if [[ -n "$ZI_ZSH_VERSION" ]]; then
  zi::pack-zsh "$ZI_ZSH_VERSION"
fi
autoload -Uz _zi; (( ${+_comps} )) && _comps[zi]=_zi

zi::setup-annexes; zi::setup-minimal
